### ISSUE TITLE
quoteExactInputSingle Error

### ISSUE THREAD

**Issue by liubin595338764** [Uniswap/v3-sdk#188]
Article address: https://docs.uniswap.org/sdk/v3/guides/quoting

```js
const quotedAmountOut = await quoterContract.callStatic.quoteExactInputSingle(
  poolConstants.token0,
  poolConstants.token1,
  poolConstants.fee,
  fromReadableAmount(
    CurrentConfig.tokens.amountIn,
    CurrentConfig.tokens.in.decimals
  ).toString(),
  0
)
```

When calling 'quoterContract. callStatic. quoteExactInputSingle', I often encounter this error. What is the problem?

Then it becomes normal after a period of time, occasionally appearing, but sometimes appearing continuously for more than an hour

```js
Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"to":"0xb27308f9F90D607463bb33eA1BeBb41C27CE5AB6","data":"0xf7729d430000000000000000000000006b175474e89094c44da98b954eedeac495271d0f000000000000000000000000dac17f958d2ee523a2206206994597c13d831ec7000000000000000000000000000000000000000000000000000000000000006400000000000000000000000000000000000000000000003635c9adc5dea000000000000000000000000000000000000000000000000000000000000000000000","accessList":null}, error={"reason":"missing response","code":"SERVER_ERROR","requestBody":"{\"method\":\"eth_call\",\"params\":[{\"to\":\"0xb27308f9f90d607463bb33ea1bebb41c27ce5ab6\",\"data\":\"0xf7729d430000000000000000000000006b175474e89094c44da98b954eedeac495271d0f000000000000000000000000dac17f958d2ee523a2206206994597c13d831ec7000000000000000000000000000000000000000000000000000000000000006400000000000000000000000000000000000000000000003635c9adc5dea000000000000000000000000000000000000000000000000000000000000000000000\"},\"latest\"],\"id\":44,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","serverError":{"errno":-54,"code":"ECONNRESET","syscall":"read"},"url":"https://eth-mainnet.g.alchemy.com/v2/Q0OFt0TlLINakeetLvkrjF6UxMaMj7Tc"}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at Logger.makeError (/Users/amir.liu/Documents/supportBusiness/uniswap-explore/quoting-koa/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/Users/amir.liu/Documents/supportBusiness/uniswap-explore/quoting-koa/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at checkError (/Users/amir.liu/Documents/supportBusiness/uniswap-explore/quoting-koa/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:108:16)
    at JsonRpcProvider.<anonymous> (/Users/amir.liu/Documents/supportBusiness/uniswap-explore/quoting-koa/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:751:47)
    at step (/Users/amir.liu/Documents/supportBusiness/uniswap-explore/quoting-koa/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/Users/amir.liu/Documents/supportBusiness/uniswap-explore/quoting-koa/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/Users/amir.liu/Documents/supportBusiness/uniswap-explore/quoting-koa/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'missing revert data in call exception; Transaction reverted without a reason string',
  code: 'CALL_EXCEPTION',
  data: '0x',
  transaction: {
    to: '0xb27308f9F90D607463bb33eA1BeBb41C27CE5AB6',
    data: '0xf7729d430000000000000000000000006b175474e89094c44da98b954eedeac495271d0f000000000000000000000000dac17f958d2ee523a2206206994597c13d831ec7000000000000000000000000000000000000000000000000000000000000006400000000000000000000000000000000000000000000003635c9adc5dea000000000000000000000000000000000000000000000000000000000000000000000',
    accessList: null
  },
  error: Error: missing response (requestBody="{\"method\":\"eth_call\",\"params\":[{\"to\":\"0xb27308f9f90d607463bb33ea1bebb41c27ce5ab6\",\"data\":\"0xf7729d430000000000000000000000006b175474e89094c44da98b954eedeac495271d0f000000000000000000000000dac17f958d2ee523a2206206994597c13d831ec7000000000000000000000000000000000000000000000000000000000000006400000000000000000000000000000000000000000000003635c9adc5dea000000000000000000000000000000000000000000000000000000000000000000000\"},\"latest\"],\"id\":44,\"jsonrpc\":\"2.0\"}", requestMethod="POST", serverError={"errno":-54,"code":"ECONNRESET","syscall":"read"}, url="https://eth-mainnet.g.alchemy.com/v2/Q0OFt0TlLINakeetLvkrjF6UxMaMj7Tc", code=SERVER_ERROR, version=web/5.7.1)
      at Logger.makeError (/Users/amir.liu/Documents/supportBusiness/uniswap-explore/quoting-koa/node_modules/@ethersproject/logger/lib/index.js:238:21)
      at Logger.throwError (/Users/amir.liu/Documents/supportBusiness/uniswap-explore/quoting-koa/node_modules/@ethersproject/logger/lib/index.js:247:20)
      at /Users/amir.liu/Documents/supportBusiness/uniswap-explore/quoting-koa/node_modules/@ethersproject/web/lib/index.js:260:36
      at step (/Users/amir.liu/Documents/supportBusiness/uniswap-explore/quoting-koa/node_modules/@ethersproject/web/lib/index.js:33:23)
      at Object.throw (/Users/amir.liu/Documents/supportBusiness/uniswap-explore/quoting-koa/node_modules/@ethersproject/web/lib/index.js:14:53)
      at rejected (/Users/amir.liu/Documents/supportBusiness/uniswap-explore/quoting-koa/node_modules/@ethersproject/web/lib/index.js:6:65)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    reason: 'missing response',
    code: 'SERVER_ERROR',
    requestBody: '{"method":"eth_call","params":[{"to":"0xb27308f9f90d607463bb33ea1bebb41c27ce5ab6","data":"0xf7729d430000000000000000000000006b175474e89094c44da98b954eedeac495271d0f000000000000000000000000dac17f958d2ee523a2206206994597c13d831ec7000000000000000000000000000000000000000000000000000000000000006400000000000000000000000000000000000000000000003635c9adc5dea000000000000000000000000000000000000000000000000000000000000000000000"},"latest"],"id":44,"jsonrpc":"2.0"}',
    requestMethod: 'POST',
    serverError: Error: read ECONNRESET
        at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
      errno: -54,
      code: 'ECONNRESET',
      syscall: 'read'
    },
    url: 'https://eth-mainnet.g.alchemy.com/v2/Q0OFt0TlLINakeetLvkrjF6UxMaMj7Tc'
  }
}
```

**Comment by kundannetsetDemo** [comment]
@liubin595338764 any update?
