### ISSUE TITLE
NonfungiblePositionManager.removeCallParameters() assumes the position liquidity is a fraction

### ISSUE THREAD

**Issue by eliotstock** [Uniswap/v3-sdk#87]
Partial stack trace:

```
/home/e/r/node_modules/@uniswap/sdk-core/src/entities/fractions/fraction.ts:38
    throw new Error('Could not parse fraction')
          ^
Error: Could not parse fraction
    at Function.tryParseFraction (/home/e/r/node_modules/@uniswap/sdk-core/src/entities/fractions/fraction.ts:38:11)
    at Percent.multiply (/home/e/r/node_modules/@uniswap/sdk-core/src/entities/fractions/fraction.ts:108:34)
    at Percent.multiply (/home/e/r/node_modules/@uniswap/sdk-core/src/entities/fractions/percent.ts:30:21)
    at Function.removeCallParameters (/home/e/r/node_modules/@uniswap/v3-sdk/src/nonfungiblePositionManager.ts:364:46)

```

Steps to repro:

* Create a v3 position programmatically.
* Find the position's token ID
* Get a Position instance for it using `const position: Position = await positionManagerContract.positions(tokenId)`
* Assume you want to remove all liquidity, so `RemoveLiquidityOptions.liquidityPercentage` is `new Percent(1)`
* Call `removeCallParameters`
* On this line: https://github.com/Uniswap/v3-sdk/blob/main/src/nonfungiblePositionManager.ts#L350, the options liquidity percentage is multiplied by the existing position liquidity, which requires that the existing position liquidity is a Fraction. Its not - it's a `BigNumber`

Also note that the docs don't explain how to get hold of an existing v3 position for passing to `removeCallParameters()`

**Comment by jwthanh** [comment]
@eliotstock did you resolve the issue or get more information?

**Comment by eliotstock** [comment]
I did not resolve the issue, nor get more info, sorry.

**Comment by jwthanh** [comment]
> I did not resolve the issue, nor get more info, sorry.

@eliotstock Could you provide more detail your first step when you create v3 position programmatically?

**Comment by eliotstock** [comment]
Sure. Here's what I do to create the position:

```
      const position = Position.fromAmounts({
        pool: rangeOrderPool,
        tickLower: this.minTick,
        tickUpper: this.maxTick,
        amount0: availableUsdc,
        amount1: availableWeth,
        useFullPrecision: true
      })
  
      const mintOptions: MintOptions = {
        slippageTolerance: CHAIN_CONFIG.slippageTolerance,
        deadline: moment().unix() + DEADLINE_SECONDS,
        recipient: wallet.address,
        createPool: false
      }
  
      const { calldata, value } = NonfungiblePositionManager.addCallParameters(position, mintOptions)
  
      const nonce = await wallet.getTransactionCount("latest")
  
      const txRequest = {
        from: wallet.address,
        to: CHAIN_CONFIG.addrPositionManager,
        value: VALUE_ZERO_ETHER,
        nonce: nonce,
        gasLimit: CHAIN_CONFIG.gasLimit,
        gasPrice: CHAIN_CONFIG.gasPrice,
        data: calldata
      }
  
      const txResponse: TransactionResponse = await wallet.sendTransaction(txRequest)

      const txReceipt: TransactionReceipt = await txResponse.wait()
```

**Comment by marktoda** [comment]
Hey EliotStock - I know it's been awhile, but are you still having this issue? If so, it would be helpful to know what version of the SDK you're using

**Comment by eliotstock** [comment]
Haven't been running this code lately, sorry. At the time I was using these versions:

```
  "dependencies": {
    "@uniswap/sdk-core": "^3.0.1",
    "@uniswap/v3-core": "^1.0.0",
    "@uniswap/v3-sdk": "^3.5.1",
   ...
  },
```

**Comment by bfinance** [comment]
im having issues minting a position with nonfungiblePositionManager. and this dont work for me: const { Pool, Position, Route, TickMath, nearestUsableTick, tickSpacing } = require('@uniswap/v3-sdk');
